# Generated by Django 3.0.3 on 2020-02-29 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NeuralModel',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=30)),
                ('execution_code_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=30)),
                ('data_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainingTask',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('user_id', models.CharField(editable=False, max_length=30)),
                ('parameters', models.CharField(editable=False, help_text='Parameters in json', max_length=4096)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('RUNNING', 'Running'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed'), ('SUCCEEDED', 'Succeeded')], max_length=30)),
                ('error_message', models.CharField(blank=True, max_length=1024)),
                ('result_url', models.URLField(blank=True)),
                ('model', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='data_storage.NeuralModel')),
                ('user_input', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='data_storage.UserInput')),
            ],
        ),
    ]
