# Generated by Django 3.0.3 on 2020-05-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuralmodel',
            name='id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trainingtask',
            name='id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trainingtask',
            name='status',
            field=models.CharField(choices=[('INITIAL', 'Initial'), ('WAITING', 'Waiting'), ('RUNNING', 'Running'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed'), ('SUCCEEDED', 'Succeeded')], max_length=30),
        ),
        migrations.AlterField(
            model_name='userinput',
            name='id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
