# Generated by Django 3.0.3 on 2020-06-20 09:39

import data_storage.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage', '0002_auto_20200510_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvalTask',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('user_id', models.CharField(editable=False, max_length=30)),
                ('parameters', models.CharField(editable=False, help_text='Parameters in json', max_length=4096)),
                ('status', models.CharField(choices=[('INITIAL', 'Initial'), ('WAITING', 'Waiting'), ('RUNNING', 'Running'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed'), ('SUCCEEDED', 'Succeeded')], max_length=30)),
                ('error_message', models.CharField(blank=True, max_length=1024)),
                ('result_url', models.URLField(blank=True)),
                ('train_task', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='data_storage.TrainingTask')),
                ('user_input', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='data_storage.UserInput')),
            ],
            bases=(models.Model, data_storage.models.Task),
        ),
    ]
