# Generated by Django 3.0.3 on 2020-06-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage', '0004_auto_20200620_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingtask',
            name='metrics',
            field=models.CharField(blank=True, max_length=8192),
        ),
    ]
