# Generated by Django 3.0.3 on 2020-06-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage', '0005_trainingtask_metrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaltask',
            name='result_url',
        ),
        migrations.AddField(
            model_name='evaltask',
            name='result',
            field=models.CharField(blank=True, max_length=8192),
        ),
    ]
